FROM l2r-base:latest

##################################################################### 
# Info:                                                             #
#    builds onto l2r-base image by installing requirements.txt and  #
#    adding the l2r directory                                       #
#                                                                   #
# Usage:                                                            #
#    see build.bash                                                 #
#####################################################################

# Add files
COPY requirements.txt l2r.tar.gz /

# Install requirements
RUN pip3 install -r requirements.txt \
	&& tar -xzvf l2r.tar.gz && rm l2r.tar.gz

WORKDIR l2r
