# ========================================================================= #
# Filename:                                                                 #
#    workers.yaml                                                           #
#                                                                           #
# Description:                                                              #
#    Configuration for worker pods. All items with "*" will need to be      #
#    modified for your configuration                                        #
# ========================================================================= #

apiVersion: apps/v1
#kind: DaemonSet
kind: ReplicaSet
metadata:
  name: worker-pods
  labels:
    tier: worker-set
spec:
  replicas: 12
  selector:
    matchLabels:
      tier: worker-set
  template:
    metadata:
      labels:
        tier: worker-set
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: workers
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: racing-sim
           # * use your docker image
          image: 753617736767.dkr.ecr.us-east-1.amazonaws.com/arrival-sim
          command:
            - "/bin/bash"
            - "-c"
            - "sudo -u ubuntu ./ArrivalSim.sh"
        - name: worker-container
          tty: true
          stdin: true
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-key
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: access-key
          # * use your docker image
          image: 753617736767.dkr.ecr.us-east-1.amazonaws.com/l2r-node:latest
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
          command:
            - "/bin/bash"
            - "-c"
            # * replace -i with learners IP address
            - "./run.bash -s scripts/distrib_sac.py -c configs/distrib_sac.yaml -t worker -i 192.168.38.12 -p 4444"
